spring:
  application:
    name: EdgeHub

server:
  port: 8085

mqtt:
  broker: ${MQTT_BROKER}
  client-id: ${MQTT_CLIENT}
  topics: ${MQTT_TOPICS}

influx:
  url: ${INFLUX_URL}
  bucket: ${INFLUX_BUCKET}
  token: ${INFLUX_TOKEN}
  org: ${INFLUX_ORG}

sensor:
  duration: ${INIT_DATA_MINUTES}
