spring:
  application:
    name: EdgeHub

server:
  port: 8085

mqtt:
  broker: tcp://localhost:1883
  client-id: edge-hub-client
  topics: sensors/#,alerts

influx:
  bucket: sensor_data

sensor:
  duration: 60
